#Type "make all" to compile two files
all:server

#Type "make server" to compile echo_server.cpp
server: server.cpp
	g++ -std=c++11 -o server server.cpp

#Type "make clean" to clean output files
clean:
	rm -rf *.o
